schema = 1
name="Access Widener"
version = "${version}"
description = "An implementation of Fabric's AccessWidener for Felis"
modid = "access-widener"

[[entrypoints]]
id = "loader_plugin"
specifier = "felis.aw.AccessWidenerLoaderPlugin"

[[dependencies.requires]]
modid = "felis"
version = ">=1.9.0-alpha"
